### ISSUE TITLE
make command not working

### ISSUE THREAD

**Issue by ghost** [stealth/qdns#1]
when running 

> make

To try and set up qdns, I am receiving the following error:

> `c++ -Wall -std=c++11 -pedantic -O2 -c -I/usr/local/include  provider.cc
> provider.cc:25:10: fatal error: usi++/usi++.h: No such file or directory
>  #include <usi++/usi++.h>
>   ^~~~~~~~~~~~~~~
> compilation terminated.
> Makefile:29: recipe for target 'provider.o' failed
> make: *** [provider.o] Error 1

Which is preventing me from using the repository.

`

**Comment by stealth** [comment]
libusi++ not installed?
