### ISSUE TITLE
'make' encounter error

### ISSUE THREAD

**Issue by luckypoem** [stealth/qdns#2]
hi.

yudeMacBook-Air:qdns-by-stealth brite$ make
c++ -Wall -std=c++11 -pedantic -O2 -c -I/usr/local/include  provider.cc
c++ -Wall -std=c++11 -pedantic -O2 -c -I/usr/local/include  qdns.cc
qdns.cc:626:69: warning: taking address of packed member 'port' of class or
      structure 'net_headers::dns_srv_rr' may result in an unaligned pointer
      value [-Waddress-of-packed-member]
  ..."%255[^:]:%hu:%hu:%hu", name, &prio, &weight, &srv.port) != 4)
                                                    ^~~~~~~~
1 warning generated.
c++ -Wall -std=c++11 -pedantic -O2 -c -I/usr/local/include  main.cc
c++ -Wall -std=c++11 -pedantic -O2 -c -I/usr/local/include  misc.cc
c++ *.o -lusi++ -lpcap -ldnet -L/usr/local/lib -o qdns
ld: library not found for -ldnet
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1
yudeMacBook-Air:qdns-by-stealth brite$

how to fix it?
thank you.

**Comment by stealth** [comment]
Ok, so this is an OSX build?
qdns is only for linux so far :( (requires libdnet obviously)
If it should be a Linux install on an macbook, you need to install libdnet and libusi++
for raw packet sends

**Comment by stealth** [comment]
If you already have libusi++ installed, (and apparently it doesnt need libdnet),
you can try removing the line

LIBS+=-ldnet

from Makefile
